blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }
    requirements:
        method:  GET

blog_about:
    path:     /about
    defaults: { _controller: BlogBundle:Blog:about }

blog_contact:
    path:     /contact
    defaults: { _controller: BlogBundle:Blog:contact }