
#blog_show:
#    path:     /blog/{id}/show
#    defaults: { _controller: "EurotradeBundle:blog:show" }
#    methods:  GET
#
#blog_new:
#    path:     /blog/new
#    defaults: { _controller: "EurotradeBundle:blog:new" }
#    methods:  [GET, POST]
#
#blog_edit:
#    path:     /blog/{id}/edit
#    defaults: { _controller: "EurotradeBundle:blog:edit" }
#    methods:  [GET, POST]
#
#blog_delete:
#    path:     /blog/{id}/delete
#    defaults: { _controller: "EurotradeBundle:blog:delete" }
#    methods:  DELETE
