BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '50'
        author:
            type: string
            length: 255
        post:
            type: text
        image:
            type: string
            length: '50'
        date:
            type: datetime
        comment:
            type: text
    lifecycleCallbacks: {  }
